### ISSUE TITLE
Bug#1 : NPE in search() method if the key does not exist

### ISSUE THREAD

**Issue by vaibhav6451956** [vaibhav6451956/DataStructures#2]
The search() method is throwing an NPE if the searched key does not exist in the tree:

Exception in thread "main" java.lang.NullPointerException
	at com.vaibhav.coursera.trees.BinarySearchTreeImpl.search(BinarySearchTreeImpl.java:131)
	at com.vaibhav.coursera.trees.BinarySearchTreeImpl.search(BinarySearchTreeImpl.java:138)
	at com.vaibhav.coursera.trees.BinarySearchTreeImpl.search(BinarySearchTreeImpl.java:135)
	at com.vaibhav.coursera.trees.BinarySearchTreeImpl.search(BinarySearchTreeImpl.java:138)
	at com.vaibhav.coursera.trees.BinarySearchTreeImpl.search(BinarySearchTreeImpl.java:138)
	at com.vaibhav.coursera.trees.BinarySearchTreeImpl.search(BinarySearchTreeImpl.java:121)
	at com.vaibhav.coursera.trees.BSTTest.main(BSTTest.java:30)

**Comment by vaibhav6451956** [comment]
Fixed by bf2ee7525401b2e218fac77ac1d83133dd3136af

**Comment by vaibhav6451956** [comment]
Closing the bug now
